### ISSUE TITLE
Error: A value of type 'bool Function()' can't be assigned to a variable of type 'bool'.

### ISSUE THREAD

**Issue by shubham-indalkar** [liodali/osm_flutter#377]
Hello, I am getting this error in latest version (0.42.0) of the package.

```
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_osm_plugin-0.42.0/lib/src/widgets/mobile_osm_flutter.dart:216:26: Error: A value of type 'bool Function()' can't be assigned to a variable of type 'bool'.
[   +5 ms]       if (locationStatus.isGranted) {
[        ]                          ^                                   
```

Tried `flutter pub get` and `flutter clean`. 

Output of `flutter doctor`:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.19045.2604], locale en-US)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android 
SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.2)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.75.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```

**Comment by liodali** [comment]
are you using permission_handler also in your app ?

**Comment by shubham-indalkar** [comment]
> are you using permission_handler also in your app ?

No, I'm not using permission_handler.
These are the packages I'm using.
```
dependencies:
  accordion: ^2.5.1
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_osm_plugin: ^0.42.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.6
  fluttertoast: 8.1.1
  geolocator: ^9.0.2
  intl: ^0.18.0
  introduction_screen: ^3.1.2
  lottie: ^2.0.0
  multiavatar: ^0.1.5
  otp_text_field: ^1.1.3
  persistent_bottom_nav_bar_v2: ^4.2.6
  pinput: ^2.2.21
  qr_code_scanner: ^1.0.1
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15
  sidebarx: ^0.14.0
  slide_to_confirm: ^1.1.0
  sms_autofill: ^2.2.0
  stop_watch_timer: ^2.0.0
  url_launcher: ^6.1.7
```

**Comment by liodali** [comment]
try to use 
```yaml
dependency_overrides:
        permission_handler: ^10.2.0
```

**Comment by shubham-indalkar** [comment]
> try to use
> 
> ```yaml
> dependency_overrides:
>         permission_handler: ^10.2.0
> ```

The error persists even after adding above lines in pubspec.

**Comment by shubham-indalkar** [comment]
When building the apk via GitHub action workflow. It is building the apk. 
This is the workflow:
```
name: Flutter Workflow
'on':
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
```

On my system the Java version is 19.0.1. Is this what causing the problem?

Thanks.

**Comment by liodali** [comment]
we published new version `0.50.0` try it

**Comment by liodali** [comment]
is your issue still exist ?

**Comment by shubham-indalkar** [comment]
> we published new version `0.50.0` try it

The issue still exist even after updating to latest version. The apk builds fine on GitHub workflow which uses same flutter version but Java version 17. 

![IMG_20230303_180210](https://user-images.githubusercontent.com/21367218/222772263-6ee2b968-7b00-4094-a82d-320f4d41f81c.png)

**Comment by liodali** [comment]
did you try to update flutter version ?

**Comment by shubham-indalkar** [comment]
> did you try to update flutter version ?

No. My project requirement is Flutter 3.3.9. 
I installed on another system and it's working fine.
